name: OsVigaristas
options:
  bundleIdPrefix: gabrielAmaral
  deploymentTarget:
    iOS: "18.0"
  productName: Os Vigaristas
  createIntermediateGroups: true

targets:
  OsVigaristas:
    type: application
    platform: iOS
    sources:
      - path: OsVigaristas
    resources:
      - path: OsVigaristas/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: gabrielAmaral.OsVigaristas
        CURRENT_PROJECT_VERSION: 1
        INFO_PLIST_FILE: OsVigaristas/Info.plist
        TARGETED_DEVICE_FAMILY: "1" # iPhone (1)
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: YES
        DEVELOPMENT_TEAM: 7N9YG996K2
        CODE_SIGN_ENTITLEMENTS: OsVigaristas/OsVigaristas.entitlements
        
    capabilities:
      - signInWithApple: {}
