name: Dingo
options:
  bundleIdPrefix: eumesmo
  deploymentTarget:
    iOS: "18.0"
  productName: Dingo
  createIntermediateGroups: true

targets:
  Dingo:
    type: application
    platform: iOS
    sources:
      - path: Shared
      - path: Dingo
      - path: Shared
    resources:
      - path: Dingo/Assets.xcassets

    settings:
      base:
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        PRODUCT_BUNDLE_IDENTIFIER: eumesmo.OsVigaristas
        CURRENT_PROJECT_VERSION: 1
        INFO_PLIST_FILE: Dingo/Info.plist
        
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIRequiresFullScreen: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: ["UIInterfaceOrientationPortrait"]
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "We need your microphone access to test the voice!"
        
        TARGETED_DEVICE_FAMILY: "1" # iPhone only
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_ENTITLEMENTS: Dingo/Dingo.entitlements
        
        INFOPLIST_KEY_CFBundleDevelopmentRegion: "pt-BR"
        INFOPLIST_KEY_CFBundleLocalizations: ["pt-BR"]

    entitlements:
      path: Dingo/Dingo.entitlements
      properties:
        com.apple.developer.applesignin:
          - Default
        com.apple.developer.icloud-services:
          - CloudKit
        com.apple.developer.icloud-container-identifiers:
          - iCloud.eumesmo.OsVigaristas
        aps-environment: "development"
        com.apple.security.app-sandbox: true
        com.apple.developer.ubiquity-kvstore-identifier: "$(TeamIdentifierPrefix)$(CFBundleIdentifier)"
    
# Capabilities só dependem dos entitlemnts.
#    Precisa melhorar para ter todos as capabilities necessarias
    capabilities:
      pushNotifications:
      signInWithApple:
      iCloud:
        services: ["CloudKit"]
        containers: ["iCloud.eumesmo.OsVigaristas"]
      backgroundModes:
        modes: ["remote-notification"]
